name: Deploy Storybook to GitHub Pages

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Pnpm install
        run: pnpm install

      - name: Build Storybook
        run: |
          pnpm build-storybook
          mkdir -p dist/storybook/
          mv ./storybook-static/* ./dist/storybook/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./dist
